name: build

on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1.3.0
        with:
          install: true
          version: latest
          driver-opts: image=moby/buildkit:master
      - name: Login to GitHub Packages Docker Registry
        uses: docker/login-action@v1.10.0
        with:
          registry: ghcr.io
          username: jenkins-arvato
          password: ${{ secrets.CR_PAT }}
      - name: Build and Push
        uses: docker/build-push-action@v2.4.0
        with:
          push: true
          pull: true
          tags: ghcr.io/arvatoaws-labs/terraform-pipeline:latest
          cache-from: type=registry,ref=ghcr.io/arvatoaws-labs/terraform-pipeline:latest
          cache-to: type=inline