name: build

on:
  push:
    branches:
    - main
    - master
  schedule:
  - cron: '30 12 * * 3'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3.4.0
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v2.5.0
      with:
        install: true
        version: latest
        driver-opts: image=moby/buildkit:master
    - name: Login to GitHub Packages Docker Registry
      uses: docker/login-action@v2.1.0
      with:
        registry: ghcr.io
        username: ${{github.actor}}
        password: ${{ secrets.GITHUB_TOKEN }}        
        #username: jenkins-arvato
        #password: ${{ secrets.CR_PAT }}
    - name: Build and Push
      uses: docker/build-push-action@v5.1.0
      with:
        push: true
        pull: true
        tags: ghcr.io/arvatoaws-labs/terraform-pipeline:latest
        cache-from: type=registry,ref=ghcr.io/arvatoaws-labs/terraform-pipeline:latest
        cache-to: type=inline
